DROP DATABASE IF EXISTS PHPVanillaMVC;
CREATE DATABASE PHPVanillaMVC CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE PHPVanillaMVC;

CREATE TABLE productos (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCTO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(6,2) NOT NULL,
    IMAGEN VARCHAR(200),
    FECHA_ALTA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO TINYINT(1) NOT NULL DEFAULT 1
)engine=InnoDB;

INSERT INTO `productos` (`ID`, `PRODUCTO`, `DESCRIPCION`, `PRECIO`, `IMAGEN`, `FECHA_ALTA`, `ESTADO`) VALUES
(1, 'Pizza Margarita', 'Una pizza clásica italiana', 8.99, '/assets/img/pizza/margarita.jpeg', '2024-02-10 14:45:00', 1),
(2, 'Pizza Anana', 'Una pizza de carácter aromático', 9.50, '/assets/img/pizza/anna.jpeg', '2024-02-10 14:45:00', 1),
(3, 'Bebida cola', 'sabor original', 1.75, '/assets/img/bebidas/cocacola.png', '2024-03-05 11:20:00', 1);

CREATE TABLE categorias (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(100) NOT NULL UNIQUE
)engine=InnoDB;

INSERT INTO categorias (CATEGORIA) VALUES 
('Pizza'),
('Bebidas'),
('Postres'),
('Pastas'),
('Cafeteria');

CREATE TABLE categorizacion (
    FKPRODUCTO INT UNSIGNED NOT NULL,
    FKCATEGORIA INT UNSIGNED NOT NULL,
    PRIMARY KEY (FKPRODUCTO, FKCATEGORIA),
    CONSTRAINT CATEGORIZACION_PRODUCTO FOREIGN KEY (FKPRODUCTO) REFERENCES productos(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CATEGORIZACION_CATEGORIA FOREIGN KEY (FKCATEGORIA) REFERENCES categorias(ID) ON DELETE CASCADE  
)engine=InnoDB;

INSERT INTO categorizacion (FKPRODUCTO, FKCATEGORIA) VALUES 
(1, 1),
(2, 1),
(3, 2);
