DROP DATABASE IF EXISTS crud_catalogo;
CREATE DATABASE crud_catalogo CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE crud_catalogo;

CREATE TABLE productos (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    PRECIO DECIMAL(6,2) NOT NULL,
    IMAGEN VARCHAR(200),
    FECHA_ALTA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO TINYINT(1) NOT NULL DEFAULT 1
)engine=InnoDB;

INSERT INTO productos (NOMBRE, PRECIO, FECHA_ALTA) VALUES 
('Pizza Margarita', 8.99, '2024-01-15 12:30:00'),
('Pizza Anana', 9.50, '2024-02-10 14:45:00'),
('Bebida cola', 1.75, '2024-03-05 11:20:00');


CREATE TABLE categorias (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
)engine=InnoDB;

INSERT INTO categorias (NOMBRE) VALUES 
('Pizza'),
('Bebidas'),
('Postres'),
('Pastas'),
('Cafeteria');

CREATE TABLE categorizacion (
    FKPRODUCTO INT UNSIGNED NOT NULL,
    FKCATEGORIA INT UNSIGNED NOT NULL,
    PRIMARY KEY (FKPRODUCTO, FKCATEGORIA),
    CONSTRAINT CATEGORIZACION_PRODUCTO FOREIGN KEY (FKPRODUCTO) REFERENCES productos(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CATEGORIZACION_CATEGORIA FOREIGN KEY (FKCATEGORIA) REFERENCES categorias(ID) ON DELETE CASCADE  
)engine=InnoDB;

INSERT INTO categorizacion (FKPRODUCTO, FKCATEGORIA) VALUES 
(1, 1),
(2, 1),
(3, 2);
